### ISSUE TITLE
Bad Gateway Error (502)

### ISSUE THREAD

**Issue by pampeffyALT** [pavo-etc/minecraftle#9]
The website (minecraftle.zachmanson.com) is consistantly giving me a 502 bad gateway error, and isn't just me. Image attached below. Reloading and other client-side fixes do not work. Maybe a restart or something similar will fix it?
![IMG_5555](https://github.com/pavo-etc/minecraftle/assets/140517805/1aae8347-2e53-45b8-b166-5b4d469f8a53)

**Comment by pavo-etc** [comment]
Restarting the server resolved this.  Not sure what happened but will investigate further if it happens again.

**Comment by pavo-etc** [comment]
@gsoneill did not know about this, what discord servers?

**Comment by gsoneill** [comment]
cubfan135 and zedaph afaik. there's likely others. we play pretty regularly and love the game!

**Comment by pampeffyALT** [comment]
But I saw that the 502 website error happened... again. Everything is the exact same as the first time. Probably because of the influx of users, but thought that I should let you know.
![IMG_5626](https://github.com/pavo-etc/minecraftle/assets/140517805/f1678a53-09bd-4239-8d00-9d210417aa82)

**Comment by pavo-etc** [comment]
I've restarted the server, clearly a recurring issue so I'll look into resolving it.  Assuming it's just higher traffic that causes it for the moment but will investigate properly.

**Comment by Pietagorh** [comment]
I get this error, kinda different but probably related trying to see my stats ![Screenshot_20231016-210206.png](https://github.com/pavo-etc/minecraftle/assets/60353007/25a5fad9-44d1-442d-a07a-134aa1627579)

**Comment by pavo-etc** [comment]
I think these are two separate issues. I've mitigated the Internal Server error, appears to have the following error in logs.
```
Oct 17 00:28:59 trackstar-22 uwsgi[184471]: Tue Oct 17 00:28:59 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stats/<userid> (ip <ip>) !!!
Oct 17 00:28:59 trackstar-22 uwsgi[184471]: Tue Oct 17 00:28:59 2023 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /stats/<userid> (<ip>)
Oct 17 00:28:59 trackstar-22 uwsgi[184471]: OSError: write error
```

**Comment by pavo-etc** [comment]
This is a log from the 502 error
```
Oct 17 16:58:00 trackstar-22 uwsgi[184474]: uwsgi_response_write_body_do() TIMEOUT !!!
Oct 17 16:58:00 trackstar-22 uwsgi[184474]: OSError: write error
Oct 17 16:58:00 trackstar-22 uwsgi[184474]: [pid: 184474|app: 0|req: 84907/435029] 86.42.4.182 () {58 vars in 1118 bytes} [Tue Oct 17 16:53:59 2023] GET /static/audio/C418%20-%20Aria%20Math%20(Minecraft%20Volum>
Oct 17 16:58:00 trackstar-22 uwsgi[184475]: [2023-10-17 16:54:07,932] ERROR in app: Exception on /api/submitgame [GET]
Oct 17 16:58:00 trackstar-22 uwsgi[184475]: Traceback (most recent call last):
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:     response = self.full_dispatch_request()
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:     rv = self.handle_user_exception(e)
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:     rv = self.dispatch_request()
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:   File "/root/minecraftle/./app/routes.py", line 156, in submitstats
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:     response["succeeded"] = database.insert_record(user_id, today, int(win), int(attempts))
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:   File "/root/minecraftle/./app/database.py", line 49, in insert_record
Oct 17 16:58:00 trackstar-22 uwsgi[184475]:     cursor.execute("SELECT * FROM games_played WHERE user_id==? AND date==?", (user_id, date))
Oct 17 16:58:00 trackstar-22 uwsgi[184475]: sqlite3.OperationalError: database is locked
```

**Comment by pavo-etc** [comment]
Splitting this issue into two, the 500 error is different in origin, has been moved to #10

**Comment by pavo-etc** [comment]
This is what I get for running on the cheapest digitalocean droplet

**Comment by pavo-etc** [comment]
```
Oct 25 17:00:18 trackstar-22 uwsgi[732]: [pid: 732|app: 0|req: 97643/517533] <ipaddr> () {56 vars in 1085 bytes} [Wed Oct 25 17:00:18 2023] GET /static/icons/apple-touch-icon.png => generated 0 bytes in 39 msecs (HTTP/1.1 304) 3 headers in 151 bytes (0 switches on core 0)
Oct 25 17:00:18 trackstar-22 uwsgi[732]: [pid: 732|app: 0|req: 97644/517534] <ipaddr> () {58 vars in 1045 bytes} [Wed Oct 25 17:00:18 2023] GET /static/audio/button_click.wav => generated 50808 bytes in 42 msecs (HTTP/1.1 206) 8 headers in 304 bytes (104 switches on core 0)
Oct 25 17:00:22 trackstar-22 uwsgi[733]: [2023-10-25 17:00:22,852] ERROR in app: Exception on /api/submitgame [GET]
Oct 25 17:00:22 trackstar-22 uwsgi[733]: Traceback (most recent call last):
Oct 25 17:00:22 trackstar-22 uwsgi[733]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
Oct 25 17:00:22 trackstar-22 uwsgi[733]:     response = self.full_dispatch_request()
Oct 25 17:00:22 trackstar-22 uwsgi[733]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
Oct 25 17:00:22 trackstar-22 uwsgi[733]:     rv = self.handle_user_exception(e)
Oct 25 17:00:22 trackstar-22 uwsgi[733]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
Oct 25 17:00:22 trackstar-22 uwsgi[733]:     rv = self.dispatch_request()
Oct 25 17:00:22 trackstar-22 uwsgi[733]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
Oct 25 17:00:22 trackstar-22 uwsgi[733]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Oct 25 17:00:22 trackstar-22 uwsgi[733]:   File "/root/minecraftle/./app/routes.py", line 156, in submitstats
Oct 25 17:00:22 trackstar-22 uwsgi[733]:     response["succeeded"] = database.insert_record(user_id, today, int(win), int(attempts))
Oct 25 17:00:22 trackstar-22 uwsgi[733]:   File "/root/minecraftle/./app/database.py", line 67, in insert_record
Oct 25 17:00:22 trackstar-22 uwsgi[733]:     connection.commit()
Oct 25 17:00:22 trackstar-22 uwsgi[733]: sqlite3.OperationalError: database is locked
Oct 25 17:00:25 trackstar-22 uwsgi[733]: [pid: 733|app: 0|req: 106216/517535] <ipaddr> () {54 vars in 1041 bytes} [Wed Oct 25 17:00:16 2023] GET /api/submitgame?user_id=16982524994360.4805189669452703&win=1&attempts=8 => generated 265 bytes in 6418 msecs (HTTP/1.1 500) 2 hea>
Oct 25 17:00:25 trackstar-22 uwsgi[733]: iron_chestplate
Oct 25 17:00:25 trackstar-22 uwsgi[734]: [2023-10-25 17:00:23,171] ERROR in app: Exception on /api/submitgame [GET]
Oct 25 17:00:25 trackstar-22 uwsgi[734]: Traceback (most recent call last):
Oct 25 17:00:25 trackstar-22 uwsgi[734]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
Oct 25 17:00:25 trackstar-22 uwsgi[734]:     response = self.full_dispatch_request()
Oct 25 17:00:25 trackstar-22 uwsgi[734]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
Oct 25 17:00:25 trackstar-22 uwsgi[734]:     rv = self.handle_user_exception(e)
Oct 25 17:00:25 trackstar-22 uwsgi[734]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
Oct 25 17:00:25 trackstar-22 uwsgi[734]:     rv = self.dispatch_request()
Oct 25 17:00:25 trackstar-22 uwsgi[734]:   File "/root/minecraftle/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
Oct 25 17:00:25 trackstar-22 uwsgi[734]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Oct 25 17:00:25 trackstar-22 uwsgi[734]:   File "/root/minecraftle/./app/routes.py", line 156, in submitstats
Oct 25 17:00:25 trackstar-22 uwsgi[734]:     response["succeeded"] = database.insert_record(user_id, today, int(win), int(attempts))
Oct 25 17:00:25 trackstar-22 uwsgi[734]:   File "/root/minecraftle/./app/database.py", line 52, in insert_record
Oct 25 17:00:25 trackstar-22 uwsgi[734]:     cursor.execute("SELECT * FROM games_played WHERE user_id==? AND date==?", (user_id, date))
Oct 25 17:00:25 trackstar-22 uwsgi[734]: sqlite3.OperationalError: database is locked
Oct 25 17:00:25 trackstar-22 uwsgi[733]: Wed Oct 25 17:00:23 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /?random=True (ip <ipaddr>) !!!
Oct 25 17:00:25 trackstar-22 uwsgi[733]: Wed Oct 25 17:00:23 2023 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /?random=True (<ipaddr>)
Oct 25 17:00:25 trackstar-22 uwsgi[734]: [pid: 734|app: 0|req: 99579/517536] <ipaddr> () {54 vars in 1043 bytes} [Wed Oct 25 17:00:17 2023] GET /api/submitgame?user_id=16965432746200.45290274007140696&win=1&attempts=3 => generated 265 bytes in 5569 msecs (HTTP/1.1 500) 2 head>
Oct 25 17:00:25 trackstar-22 uwsgi[733]: OSError: write error
Oct 25 17:00:25 trackstar-22 uwsgi[733]: [pid: 733|app: 0|req: 106217/517537] <ipaddr> () {58 vars in 1122 bytes} [Wed Oct 25 17:00:22 2023] GET /?random=True => generated 0 bytes in 501 msecs (HTTP/1.1 200) 2 headers in 0 bytes (0 switches on core 0)
Oct 25 17:00:25 trackstar-22 uwsgi[733]: iron_bars
Oct 25 17:00:25 trackstar-22 uwsgi[733]: Wed Oct 25 17:00:23 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request / (ip <ipaddr>) !!!
Oct 25 17:00:25 trackstar-22 uwsgi[733]: Wed Oct 25 17:00:23 2023 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET / (<ipaddr>)
Oct 25 17:00:25 trackstar-22 uwsgi[733]: OSError: write error
Oct 25 17:00:25 trackstar-22 uwsgi[734]: [pid: 734|app: 0|req: 99580/517539] <ipaddr> () {58 vars in 1045 bytes} [Wed Oct 25 17:00:23 2023] GET /static/audio/button_click.wav => generated 50808 bytes in 414 msecs (HTTP/1.1 206) 8 headers in 304 bytes (104 switches on core 0)
Oct 25 17:00:25 trackstar-22 uwsgi[733]: [pid: 733|app: 0|req: 106218/517539] <ipaddr> () {56 vars in 1091 bytes} [Wed Oct 25 17:00:23 2023] GET / => generated 0 bytes in 409 msecs (HTTP/1.1 200) 2 headers in 0 bytes (0 switches on core 0)
Oct 25 17:00:25 trackstar-22 uwsgi[734]: 16982531219020.7180574907606811 1 7
Oct 25 17:00:25 trackstar-22 uwsgi[733]: oak_slab
Oct 25 17:00:25 trackstar-22 uwsgi[733]: [pid: 733|app: 0|req: 106219/517540] <ipaddr> () {56 vars in 1097 bytes} [Wed Oct 25 17:00:23 2023] GET /?random=True => generated 4352 bytes in 411 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
Oct 25 17:00:25 trackstar-22 uwsgi[733]: [pid: 733|app: 0|req: 106220/517541] <ipaddr> () {50 vars in 982 bytes} [Wed Oct 25 17:00:24 2023] GET /static/images/button-background.png => generated 0 bytes in 531 msecs (HTTP/1.1 304) 3 headers in 152 bytes (0 switches on core 0)
Oct 25 17:00:25 trackstar-22 uwsgi[733]: 16982531594830.7862078814883411 1 4
Oct 25 17:01:30 trackstar-22 uwsgi[625]: SIGINT/SIGTERM received...killing workers...
Oct 25 17:01:30 trackstar-22 systemd[1]: minecraftle.service: A process of this unit has been killed by the OOM killer.
Oct 25 17:01:31 trackstar-22 uwsgi[625]: worker 1 buried after 1 seconds
Oct 25 17:01:31 trackstar-22 uwsgi[625]: worker 2 buried after 1 seconds
Oct 25 17:01:31 trackstar-22 uwsgi[625]: worker 3 buried after 1 seconds
Oct 25 17:01:31 trackstar-22 uwsgi[625]: worker 4 buried after 1 seconds
Oct 25 17:01:31 trackstar-22 uwsgi[625]: worker 5 buried after 1 seconds
Oct 25 17:01:31 trackstar-22 uwsgi[625]: goodbye to uWSGI.
Oct 25 17:01:31 trackstar-22 uwsgi[625]: VACUUM: unix socket minecraftle.sock removed.
Oct 25 17:01:31 trackstar-22 systemd[1]: minecraftle.service: Failed with result 'oom-kill'.
Oct 25 17:01:31 trackstar-22 systemd[1]: minecraftle.service: Consumed 2h 44min 22.691s CPU time.


```

**Comment by pavo-etc** [comment]
Should automatically restart on crash now after 5 seconds

**Comment by pavo-etc** [comment]
Memory leak hmmmmm

**Comment by pavo-etc** [comment]
OSErrors piling up, never closing those db connections perhaps
